### ISSUE TITLE
Total - Available = Total Used

### ISSUE THREAD

**Issue by i8beef** [frncsdrk/node-red-contrib-linux-memory#1]
Im having trouble figuring out how to use the percentage settings in a meaningful way... I'd expect to have a few more options here, where for instance you'd have Total, Free and Used... but none of the values here really seem to fully align with those three... Available is close to "free" in the way I'm looking here, but I don't see a way to get used that would be more like Total - Available... Is there anyway to get that?

**Comment by frncsdrk** [comment]
@i8beef Could you provide a specific example, preferably with absolute values?
Are you using the `actively used memory` under `excl. buffer / cache` or `used memory` under `incl. buffer / cache`?
The amount of `actively used memory` in `excl. buffer / cache` and `used memory` in `incl. buffer / cache` are directly calculated by the [systeminformation package](https://github.com/sebhildebrandt/systeminformation). They map to `memory.active` and `memory.used`, respectively. `active` excludes buffer and cache and `used` includes it like the headers in the edit section of the module state. Maybe this is where the discrepancy is originating from?

**Comment by i8beef** [comment]
Linux treats memory reporting kinda differently... what I'm looking for really is the real equivalents of the three items under `incl. buffer / cache`, but for `excl. buffer / cache`, i.e., Free + Used = Total.

The stats you are returning from systeminformation I would consider misleading... they are going to present a picture of a machine under memory pressure. `Display total available memory` is actually what I'd consider `Free` in my case, and really I'm just looking for a second value that is the equivalent of `Total - Available = Used`.

I.e., it seems that `Display total available memory` is missing its sister variable. When both those are checked with `Display relative values`, then the percentages would be accurate to 100% of system memory I believe, whereas right now it doesn't seem theres another variable to pair with it to achieve that.

Note: systeminformation doesn't seem to EXPOSE a stat for this, so the value would literally be calculated I think by `Total - Available = Used`

**Comment by frncsdrk** [comment]
There was actually a bug with available memory that only occured when showing relative values which is now fixed and available in v0.5.2 . Maybe that already fixes your issue.

**Comment by i8beef** [comment]
I'd expect if I selected all of the check boxes in `excl. buffer / cache` except `Display total available memory` that they would add up to memory total. Mine DON'T. I'd expect if I DID select `Display total available memory` with this extra sister checkbox I'm talking about, that THOSE two would add up to memory total.

I would further expect `Display used memory by buffers and cache` + `Display free actively usable memory` = `Display total available memory` (i.e., they are a more granular view of that dimension) if I understand these right...

Perhaps this changed upstream? I see the theres a [commented](https://github.com/sebhildebrandt/systeminformation/blob/master/lib/memory.js#L146) out different version of `active` that calculates much differently. They took to just pulling "Active" from /proc/meminfo, which does NOT seem to match what I THINK they meant it.

**Comment by i8beef** [comment]
Note: RedHat's free to /proc/memInfo mapping (https://access.redhat.com/solutions/406773) actually gives the calculation I think I'm looking for for the `-/+ buffers/cache: used` and `-/+ buffers/cache: free`...

**Comment by frncsdrk** [comment]
> I'd expect if I selected all of the check boxes in excl. buffer / cache except Display total available memory that they would add up to memory total. Mine DON'T. I'd expect if I DID select Display total available memory with this extra sister checkbox I'm talking about, that THOSE two would add up to memory total.

It is not intended that they match up this way. I think you need to forget about these categories. At the time I came up with this it made sense, now I see why it might not. I think I need to rework that. If you like, have a look at `memory.js`: In combination with the `systeminformation` package docs I think it will get clearer.

**Comment by i8beef** [comment]
A version or so back, "free" changed its formatting (that RedHat document shows how the mapping of what it shows now changed) for similar reasons: free was confusing as hell and required MATH just to figure out what memory was in use. They simplified it a bit, with the calculations kind of wrapped up in the command itself to be more useful (again, detailed in that RedHat doc).

Reading the through what systeminformation exposes, I think one could do all of the same math with the EXCEPTION that systeminformation doesn't seem to provide the "slab" count necessary for complete buff/cache/slab total.

Does any of this (the excl buffers calculations) sound like something you'd actually implement? If not Ill just write my own node that maybe just exposes the complete footprint of systeminformation or another library in a similar way, I just didn't want to go off writing something new when your node is actually pretty close to what I'd build anyway. No worries though if that's not in the cards.

**Comment by frncsdrk** [comment]
I would be very happy to accept it as a PR if that is OK with you.

**Comment by i8beef** [comment]
I can do that. Do you have any guidelines you'd like me to follow regarding the existing functionality? I.e., should I make the changes to this *I* think should be made, and then you can move around as you see fit from the PR, or should I leave the existing values alone and just add new ones to the `excl. buffer / cache` section?

**Comment by frncsdrk** [comment]
I would prefer if you would add them into a new category first since these values are not just derived from `systeminformation` and probably need additional explanation.
I reorganized the categories by the way and added some additional info to hopefully make things clearer.

**Comment by i8beef** [comment]
So I did play with this but I couldn't get numbers to line up.

`systeminfo` is actually the culprit. That "active" value they pull ends up being wrong. I assume they changed it to try and account for `slab` in the `buffcache` value once `free` changed to include that in the calculations... because they ALSO changed [how buffcache is calculated](https://github.com/sebhildebrandt/systeminformation/blob/master/lib/memory.js#L150) so its calculated off of that bad `active` value.

I reverted everything and edited that instead to use the original `buffcache` and `active` calculation, and suddenly all the numbers line up better and your classifications make more sense. Ill add a bug to systeminfo instead for them to fix upstream.

**Comment by i8beef** [comment]
https://github.com/sebhildebrandt/systeminformation/issues/290

**Comment by frncsdrk** [comment]
Great! Thank you!

**Comment by i8beef** [comment]
He just released 4.15.2 which should have the correct adjustments in it.

**Comment by frncsdrk** [comment]
Updated `systeminformation` to `4.15.3` and published version `0.6.2`. Thank you for your work! If there are any more issues please let me know.

**Comment by i8beef** [comment]
Worked! Thank you!

BTW he had me expose buffers, cache and slab as distinct values on the result you could output as well. `buffcache` now includes `slab` in the calculation, but does return the three added together so you're still good there. Im not saying to do this, Im just letting you know in case it ever comes up. I'm happy with current result!
